# ***Apply Bayes' Theorem to solve a medical diagnosis problem given conditional probabilities***

Let's assume a scenario where:

𝑃
(
Disease
)
=
0.01
P(Disease)=0.01 (prior probability of having the disease)
𝑃
(
Positive Test
∣
Disease
)
=
0.99
P(Positive Test∣Disease)=0.99 (probability of testing positive if you have the disease)
𝑃
(
Positive Test
∣
No Disease
)
=
0.05
P(Positive Test∣No Disease)=0.05 (probability of testing positive if you do not have the disease)
We want to find
𝑃
(
Disease
∣
Positive Test
)
P(Disease∣Positive Test), the probability of having the disease given a positive test result.

Bayes' Theorem:
𝑃
(
Disease
∣
Positive Test
)
=
𝑃
(
Positive Test
∣
Disease
)
⋅
𝑃
(
Disease
)
𝑃
(
Positive Test
)
P(Disease∣Positive Test)=
P(Positive Test)
P(Positive Test∣Disease)⋅P(Disease)
​


Where:
𝑃
(
Positive Test
)
=
𝑃
(
Positive Test
∣
Disease
)
⋅
𝑃
(
Disease
)
+
𝑃
(
Positive Test
∣
No Disease
)
⋅
𝑃
(
No Disease
)
P(Positive Test)=P(Positive Test∣Disease)⋅P(Disease)+P(Positive Test∣No Disease)⋅P(No Disease)

In [1]:
# Given probabilities
P_disease = 0.01
P_positive_given_disease = 0.99
P_positive_given_no_disease = 0.05

# Calculating P(Positive Test)
P_no_disease = 1 - P_disease
P_positive = (P_positive_given_disease * P_disease) + (P_positive_given_no_disease * P_no_disease)

# Applying Bayes' Theorem
P_disease_given_positive = (P_positive_given_disease * P_disease) / P_positive

P_disease_given_positive


0.16666666666666669

Let's consider a 2x2 matrix
𝐴
A:
𝐴
=
(
4
1
2
3
)
A=(
4
2
​
  
1
3
​
 )

In [2]:
import numpy as np

# Define the matrix
A = np.array([[4, 1], [2, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors


(array([5., 2.]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))

Let's consider a 3x3 matrix
𝐵
B:
𝐵
=
(
2
−
1
0
−
1
2
−
1
0
−
1
2
)
B=
​
  
2
−1
0
​
  
−1
2
−1
​
  
0
−1
2
​
  
​


In [3]:
# Define the matrix
B = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])

# Calculate determinant
determinant = np.linalg.det(B)

# Calculate inverse if the determinant is non-zero
if determinant != 0:
    inverse = np.linalg.inv(B)
else:
    inverse = None

determinant, inverse


(4.0,
 array([[0.75, 0.5 , 0.25],
        [0.5 , 1.  , 0.5 ],
        [0.25, 0.5 , 0.75]]))

Let's calculate probabilities using the normal distribution. Suppose
𝜇
=
0
μ=0 and
𝜎
=
1
σ=1 (standard normal distribution). We want to find the probability
𝑃
(
𝑋
<
1.96
)
P(X<1.96).

In [4]:
import scipy.stats as stats

# Define the mean and standard deviation
mu = 0
sigma = 1

# Calculate the cumulative distribution function (CDF) for P(X < 1.96)
prob = stats.norm.cdf(1.96, mu, sigma)

prob


0.9750021048517795